title: Intaglio Demo
email: kckhchen@gmail.com
description: A site to demonstrate the blog posts processed by the tool Intaglio.
baseurl: "/intaglio-demo"
url: "kckhchen.com"
permalink: /:title/
github_username: kckhchen

markdown: kramdown
theme: minima
